### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'load_video'

### ISSUE THREAD

**Issue by ale152** [epic-kitchens/epic-kitchens-100-narrator#24]
I tried to install the narrator on Windows and at startup it produces a few errors:

```
(epic_narrator.py:18044): Gtk-WARNING **: 22:26:50.823: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_concat_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_imem_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_mms_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_realrtsp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_srt_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libaccess_wasapi_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libattachment_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libcdda_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libdcp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libdshow_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libdtv_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libdvdnav_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libdvdread_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libfilesystem_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libftp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libhttps_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libhttp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libidummy_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libimem_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\liblibbluray_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\liblive555_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libnfs_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\librtp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libsatip_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libscreen_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libsdp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libsftp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libshm_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libsmb_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libtcp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libtimecode_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libudp_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libvcd_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libvdr_plugin.dll
[000001d0d333d020] main libvlc error: stale plugins cache: modified C:\Program Files\VideoLAN\VLC\plugins\access\libvnc_plugin.dll
```
and after many more lines of dlls:
```
[000001d0e08203e0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d0e081fa80] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d0e0820a20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
Traceback (most recent call last):
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\ui.py", line 571, in ready
    self.controller.ui_video_area_ready(widget)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\controller.py", line 253, in ui_video_area_ready
    self.player = Player(widget, self)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\player.py", line 20, in __init__
    self.set_vlc_window(widget, controller.this_os)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\player.py", line 71, in set_vlc_window
    gdkdll = ctypes.CDLL("libgdk-3-0.dll")
  File "C:\Users\***\AppData\Local\Continuum\miniconda3\envs\epic_narrator\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

When I try to open a video file (that doesn't show up when "video files" is selected, it must be set on "all files"), this new error is produced and the video isn't loaded:
```
[000001d0e08203e0] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d0e081fa80] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[000001d0e0820a20] mmdevice audio output error: cannot initialize COM (error 0x80010106)
Traceback (most recent call last):
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\ui.py", line 571, in ready
    self.controller.ui_video_area_ready(widget)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\controller.py", line 253, in ui_video_area_ready
    self.player = Player(widget, self)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\player.py", line 20, in __init__
    self.set_vlc_window(widget, controller.this_os)
  File "C:\Users\***\Downloads\epic-kitchens-100-narrator-master\player.py", line 71, in set_vlc_window
    gdkdll = ctypes.CDLL("libgdk-3-0.dll")
  File "C:\Users\***\AppData\Local\Continuum\miniconda3\envs\epic_narrator\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
````

**Comment by dmoltisanti** [comment]
Hi Alessandro, unfortunately running the narrator on Windows requires some work. Although all libraries are theoretically available on Windows, the sad truth is that many of them don't really work well on Windows. I personally gave up some time ago, but could you share here what steps you followed to try to install the narrator? It seems you got pretty far :)

**Comment by ale152** [comment]
Hi Davide!

I actually simply downloaded the repo and followed the steps for conda. I ran `conda env create -f environment.yml` and then ran the script.

**Comment by dmoltisanti** [comment]
I see, I'm afraid that's not enough on Windows since some libraries need some manual installation.

I remember spending quite some time trying to make it work before eventually giving up, sorry :/

Some people managed to install flatpak apps on Ubuntu for Windows: https://blogs.gnome.org/alexl/2018/09/17/flatpak-on-windows/

I haven't tried myself though, so I'm afraid I cannot really help on this :(
